### ISSUE TITLE
HG_Bulk_access() does not work in read-write mode

### ISSUE THREAD

**Issue by marcvef** [mercury-hpc/mercury#192]
Hello,

I am trying to use `HG_Bulk_access()` to directly access the pointers from an existing HG bulk handle of another process (on the same node). I understand that the flags of `HG_Bulk_access()` are currently unused, so the read-only or read-write access is set when the bulk handle is created with `HG_Bulk_create()`. 

Now, if the bulk handle is created with the `HG_BULK_READ_ONLY` flag in process 1, `HG_Bulk_access()` works as expected and the pointers can be accessed in process 2. But if the `HG_BULK_READWRITE` flag is used in process 1 to create the bulk handle, the pointers cannot be accessed (not even for reading) and, therefore, their data cannot be modified either in process 2.

Am I missing something here to be able to use `HG_Bulk_access()` in read-write mode?

Note that using `HG_Bulk_access()` to access the pointers of an existing bulk handle, created with the `HG_BULK_READWRITE` flag, works in a single process setting. For example, to access the pointers to the internally allocated `buf_ptrs` array if `NULL` has been passed to `buf_ptrs` in `HG_Bulk_create()`. I believe this case is also covered by Mercury tests.

Thanks!

**Comment by soumagne** [comment]
Hi Marc, thank you for reporting that. If you are trying to access the memory from another process on the same node, I'd recommend that you use the NA shared memory plugin though since transfers in that case will be done using cross-memory attach. HG_Bulk_access is more convenient when you are accessing memory within the same process. I will look at the potential flag issue though.

**Comment by soumagne** [comment]
Ah I think I figured out what was going on in your case but to confirm can you please let me know what was the size of your data?
I believe that the bulk handle that you are creating has a size small enough that the data can actually fit in the RPC request and I also assume that you have `MERCURY_USE_EAGER_BULK` turned `ON` in the mercury cmake options. In that case, when the bulk handle is created with the `HG_BULK_READ_ONLY` flag, the data gets actually copied/encoded along with the RPC request message (to prevent an extra transfer). So when you call HG_Bulk_access() on that bulk handle, you can indeed access its data since the data has been transferred already. So in your case you get the illusion of accessing the memory of process 1 but you are actually accessing the memory of process 2 since there has been a transfer / data copy already. This mode only works with `HG_BULK_READ_ONLY`. With `HG_BULK_READWRITE`, we cannot allow the same type of optimization as we do not really know if you are only going to read or also write. Assuming we were allowing it and you were writing data in that case, it would only be reflected locally but not to the other process.

**Comment by marcvef** [comment]
Hi Jerome, thanks for your quick reply! Thanks for the clarification. I was unaware that a transfer on the na+sm plugin is using cross-memory attach.

Regarding your second post, with your explanation, the behavior makes perfect sense. Yes, Eager mode is turned on and the size is quite small (~800 bytes), because I am in the developing process and testing things out. Now, I tested the same code with `MERCURY_USE_EAGER_BULK` turned `OFF` and `HG_Bulk_access()` wouldn't work (the same way as earlier) anymore with an  `HG_BULK_READ_ONLY` created bulk handle of another process. It behaves like `HG_BULK_READWRITE`. With your explanation, this makes sense as the data is not copied along with the RPC message anymore. But is this the desired behavior, because it is not immediately clear from the documentation of `HG_Bulk_access()`? For now, I can circumvent my issue by disabling Eager mode or by using read-write handles.

**Comment by marcvef** [comment]
Further, I believe that there is another issue with `MERCURY_USE_EAGER_BULK=ON`, the na+sm plugin, and multiple segments, which might be related to the above situation. For example, when data is pulled (on process 2) from an `HG_BULK_READ_ONLY` created bulk handle (on process 1), only the first segment, i.e., the data of the first pointer in `void** buf_ptrs`, is actually transferred. I made sure the `hg_size_t* buf_sizes` are correctly set by debugging into the Mercury code. This scenario works fine with bmi+tcp. As far as I see, the transfer with na+sm works with multiple segments in the following cases: (1) `MERCURY_USE_EAGER_BULK` is turned `OFF`; (2) the bulk handle that is being pulled from is created with `HG_BULK_READWRITE`; and (3) the data is large enough so that it is not transferred along with the RPC message. Essentially, Eager mode is not used in the cases 2 and 3 implicitly.

For instance, a simple way to test this is by putting a number of `int*` (one per segment) into the array of pointers `void** buf_ptrs` when creating the bulk handle as read-only and checking what another process, that pulls the data with `HG_Bulk_transfer()`, receives. Case 3 (from the above paragraph) is triggered when 112 or more segments are used (assuming an int is 4 bytes in size). Fewer segments result in only the first segment being transferred.

Hope this helps.

**Comment by soumagne** [comment]
Thanks for letting me know. Yes I can see where there can be confusion and will fix the documentation of HG_Bulk_access. I will also have a look at the other issue.

**Comment by soumagne** [comment]
Hi Marc, sorry for the long time in getting to this. I have pushed the fix for it now, you should not encounter that problem anymore when using the sm plugin.

**Comment by marcvef** [comment]
Hi Jerome, thanks a lot for the update! I will check out the change soon.

**Comment by marcvef** [comment]
As a quick follow up. I finally got around to test your fix and it was good timing. While the fix in this thread didn't resolve the issue, 7cf076e2567d842f5066e6a203a5172f8106449f from 3 days ago did. Thanks!

**Comment by soumagne** [comment]
Oh ok, I guess I had missed the case in the first place. Thanks for letting me know.
